version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=development
      - SECRET_KEY= 'c4j2qovq*e5-jcrms4o*ya+jg1*ouudyrnq_yp^!hmo1t0xv)b'
      - DEBUG= 0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51HcMjjA5yAmOZWQNPQbSur4Ay8cj2SwCjkEaPBIoxfjSFmPRXs8cApv7uwSODMdFas4ou9sHgWKz9zCSf2eBsrxv00LQxSLp1T
      - STRIPE_TEST_SECRET_KEY=sk_test_51HcMjjA5yAmOZWQNRtAdCJRTi6WnKNUYEwnhFEvRYDp2YJpvCtgEiFFYiTtiEW3HYJ20wikUrmItdE3PVmiRceXx00OcrVQO2e
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: